### Index
GET {{baseUrl}}
Content-Type: {{contentType}}
Accept: */*

### Register
POST {{baseUrl}}{{authRouter}}/{{authRegister}}
Content-Type: {{contentType}}
Accept: */*

{
  "username": "tangzh1983",
  "password": "lipton1120",
  "confirm": "lipton1120"
}

### Login
POST {{baseUrl}}{{authRouter}}/{{authLogin}}
Content-Type: {{contentType}}
Accept: */*

{
  "username": "tangzh1983",
  "password": "lipton1120"
}

### Token
POST {{baseUrl}}{{authRouter}}/{{authToken}}
Content-Type: {{contentType}}
Accept: */*


### UserProfile
POST {{baseUrl}}{{authRouter}}/{{userProfile}}
Content-Type: {{contentType}}
Accept: */*
WWW-Authenticate: Bearer